module.exports.userService = require('./user.service')
module.exports.answerService = require('./answer.service')
module.exports.questionService = require('./question.service')
module.exports.resultService = require('./result.service')
module.exports.refreshTokenService = require('./refreshToken.service')